name: autofix.ci
on: 
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
permissions: { contents: read }
jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: npm i -fg corepack && corepack enable
      - uses: actions/setup-node@v4
        with: { node-version: lts/*, cache: "npm" }
      - run: npm install
      - run: npm run lint:fix
      - uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27
        with: { commit-message: "chore: apply automated updates" }
