name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_call:

permissions:
  contents: read
  pull-requests: write # Required for Codecov to comment on PRs
  statuses: write # Required for Codecov to update status checks

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run linter
        run: npm run lint
        
      - name: Run type check
        run: npm run test:types
        
      - name: Run tests with coverage
        run: npx vitest run --coverage
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: jsondeepl/cli
          fail_ci_if_error: false # Don't fail CI if Codecov has issues
          verbose: true # More detailed logging for debugging
