name: Run tests and upload coverage
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: npm i -fg corepack && corepack enable
      - uses: actions/setup-node@v4
        with: { node-version: lts/*, cache: "npm" }
      - run: npm install
      - run: npm run lint
      - run: npm run test
      - uses: codecov/codecov-action@v5
        with: { token: "${{ secrets.CODECOV_TOKEN }}", slug: jsondeepl/cli }
