name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write
  id-token: write # Required for npm provenance
  pull-requests: write # Required for Codecov in CI workflow
  statuses: write # Required for Codecov in CI workflow

jobs:
  ci:
    uses: ./.github/workflows/checks.yml
    
  release:
    name: Release package
    runs-on: ubuntu-latest
    needs: [ci]
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[skip release]') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Required for changelogen
          
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 'lts/*'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build package
        run: npm run build
        
      - name: Generate changelog and bump version
        run: changelogen --release --patch
        
      - name: Publish to npm
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Push changes and tags
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git push --follow-tags